-- Disposable probe credentials only; never use these roles in a deployed platform.
CREATE ROLE probe_a LOGIN PASSWORD 'fixture-a' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE probe_b LOGIN PASSWORD 'fixture-b' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE probe_a;
CREATE DATABASE probe_b;
REVOKE CONNECT, TEMPORARY ON DATABASE probe_a FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE probe_b FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE postgres FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE template1 FROM PUBLIC;
GRANT CONNECT, TEMPORARY ON DATABASE probe_a TO probe_a;
GRANT CONNECT, TEMPORARY ON DATABASE probe_b TO probe_b;
\connect probe_a
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO probe_a;
\connect probe_b
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO probe_b;
